dbt_CRPDB01_EPMADM_CI:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: DP_DW_IT_TRANSFORMER
      warehouse: TRANSFORMER_WH
      user: DBT_SVC
      database: CRPDB01
      schema: EPMADM
      threads: 16

    qa:
      type: snowflake
      role: DP_DW_IT_TRANSFORMER
      user: DBT_SVC_QA
      warehouse: TRANSFORMER_WH
      database: CRPDB01
      schema: EPMADM
      threads: 8

    uat:
      type: snowflake
      role: DP_DW_IT_TRANSFORMER
      user: DBT_SVC_UAT
      warehouse: TRANSFORMER_WH
      database: CRPDB01
      schema: EPMADM
      threads: 8

    prod:
      type: snowflake
      role: DP_DW_IT_TRANSFORMER
      user: DBT_SVC_PROD
      warehouse: TRANSFORMER_WH
      database: CRPDB01
      schema: EPMADM
      threads: 8

    ci:
      type: snowflake
      role: DP_DW_IT_TRANSFORMER
      user: DBT_SVC
      warehouse: TRANSFORMER_WH
      database: CRPDB01_CI
      schema: EPMADM
      threads: 8
