/*
================================================================================
 WORKFLOW  : wkf_FEL_COAL_FACT_LOAD
 SESSION   : s_m_FEL_COAL_RCPTS_QTY_QLTY_FACT_ins_upd
 MAPPING   : m_FEL_COAL_RCPTS_QTY_QLTY_FACT_ins_upd
 OPERATION : INSERT + UPDATE, data driven. RTR_NEW_EXIST splits on the target fact
             lookup; the unconnected DEFAULT1 group is discarded.
--------------------------------------------------------------------------------
 SOURCE    : feladm.FEL_COAL_RCPTS_QTY_QLTY_FDR   source filter on status
 LOOKUPS   : 11, all Use Any Value on multiple match. Date, sampled reason, system
             and business entity (seller and buyer) are unconnected; the receipt
             dimension, which supplies RECEIPT_KEY, the target fact, inventory
             location, commodity source, contract product and the two contract
             lookups are connected, the last two with upper trim overrides.
 TARGET    : feladm.FEL_COAL_RCPTS_QTY_QLTY_FACT   insert and update instances
--------------------------------------------------------------------------------
 PARAMETERS: $$RUN_STATUS, $$REC_STATUS (SQ filter), $$START_TIME (router)
             SESSSTARTTIME -> LAST_UPDT_TS
             :UDF.DQ_FOR_CHAR_VARCHAR   empty or all-space to ' ', else right trim
 SQ OVERRIDE : none, source filter UPPER(TRIM(STATUS_TX)) = '$$REC_STATUS' only
 PRE-SQL   : none     POST-SQL : none     TRUNCATE TARGET : no
--------------------------------------------------------------------------------
 NOTES     : A row is updated when it exists AND either its values differ or its
             feeder LAST_UPDT_TS is at or after $$START_TIME. flag_ChangedRecord is
             1 when everything MATCHES, so 0 means changed.
             The moisture and sulfur sampled measures are COMMENTED OUT of the
             comparison, annotated "decimal issues on source". Still written.
             The contract dimension is keyed on SYSTEM_NM, the text name, unlike
             the COST fact which keys it on the numeric SYSTEM_ID. Keys fall back
             to -2; RECEIPT_KEY comes from the receipt dimension, so a miss sends
             NULL into the NOT NULL primary key.
             The captured run read 286654 rows, updated 105657 and inserted 20.
================================================================================
*/

SET V_START_TIME    = TO_TIMESTAMP_NTZ('09/02/2026 22:30:11', 'MM/DD/YYYY HH24:MI:SS');
SET V_REC_STATUS    = 'ACTIVE';
SET V_RUN_STATUS    = 'C';
SET V_SESSSTARTTIME = CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ);

UPDATE feladm.FEL_COAL_RCPTS_QTY_QLTY_FACT TGT
SET
    SHP_DT_ID                 = SRC.SHP_DT_ID,
    UNLOADD_DT_ID             = SRC.UNLOADD_DT_ID,
    PRCD_DT_ID                = SRC.PRCD_DT_ID,
    OWNING_FCLTY_KEY          = SRC.OWNING_FCLTY_KEY,
    GEOG_FCLTY_KEY            = SRC.GEOG_FCLTY_KEY,
    INVTRY_LOC_KEY            = SRC.INVTRY_LOC_KEY,
    BSNS_ENTY_SLR_KEY         = SRC.BSNS_ENTY_SLR_KEY,
    BSNS_ENTY_BYR_KEY         = SRC.BSNS_ENTY_BYR_KEY,
    SAMPLED_KEY               = SRC.SAMPLED_KEY,
    CONTRACT_KEY              = SRC.CONTRACT_KEY,
    CMDTY_SRC_KEY             = SRC.CMDTY_SRC_KEY,
    CNTRCT_PROD_KEY           = SRC.CNTRCT_PROD_KEY,
    PRCD_TONS_QY              = SRC.PRCD_TONS_QY,
    SHP_TONS_QY               = SRC.SHP_TONS_QY,
    UNLOADD_TONS_QY           = SRC.UNLOADD_TONS_QY,
    FRZ_TRTMT_TONS_QY         = SRC.FRZ_TRTMT_TONS_QY,
    DUST_TRTMT_TONS_QY        = SRC.DUST_TRTMT_TONS_QY,
    UNLOADD_SMPLD_TONS_QY     = SRC.UNLOADD_SMPLD_TONS_QY,
    ASH_QLTY_PCT              = SRC.ASH_QLTY_PCT,
    SULFUR_QLTY_PCT           = SRC.SULFUR_QLTY_PCT,
    MOISTURE_QLTY_PCT         = SRC.MOISTURE_QLTY_PCT,
    BTU_PER_LB_MSR            = SRC.BTU_PER_LB_MSR,
    SO2_LBS_PER_MBTU_MSR      = SRC.SO2_LBS_PER_MBTU_MSR,
    UNLOADD_SMPLD_ASH_QY      = SRC.UNLOADD_SMPLD_ASH_QY,
    UNLOADD_SMPLD_BTU_LB_QY   = SRC.UNLOADD_SMPLD_BTU_LB_QY,
    UNLOADD_SMPLD_MOISTURE_QY = SRC.UNLOADD_SMPLD_MOISTURE_QY,
    UNLOADD_SMPLD_SULFUR_QY   = SRC.UNLOADD_SMPLD_SULFUR_QY,
    LAST_UPDT_TS              = SRC.LAST_UPDT_TS
FROM (
    SELECT
        CAST(LKP_RD.RECEIPT_KEY AS NUMBER(10,0))                                              AS RECEIPT_KEY,
        CAST(IFF(LKP_SHP.DATE_ID IS NULL, -2, LKP_SHP.DATE_ID) AS NUMBER(5,0))                AS SHP_DT_ID,
        CAST(IFF(LKP_UNL.DATE_ID IS NULL, -2, LKP_UNL.DATE_ID) AS NUMBER(5,0))                AS UNLOADD_DT_ID,
        CAST(IFF(LKP_PRC.DATE_ID IS NULL, -2, LKP_PRC.DATE_ID) AS NUMBER(5,0))                AS PRCD_DT_ID,
        CAST(IFF(LKP_IL.INVTRY_SCNDRY_FCLTY_KEY IS NULL, -2, LKP_IL.INVTRY_SCNDRY_FCLTY_KEY) AS NUMBER(10,0)) AS OWNING_FCLTY_KEY,
        CAST(IFF(LKP_IL.INVTRY_PRMRY_FCLTY_KEY IS NULL, -2, LKP_IL.INVTRY_PRMRY_FCLTY_KEY) AS NUMBER(10,0))   AS GEOG_FCLTY_KEY,
        CAST(IFF(LKP_IL.INVTRY_LOC_KEY IS NULL, -2, LKP_IL.INVTRY_LOC_KEY) AS NUMBER(10,0))   AS INVTRY_LOC_KEY,
        CAST(IFF(LKP_SLR.BSNS_ENTY_KEY IS NULL, -2, LKP_SLR.BSNS_ENTY_KEY) AS NUMBER(10,0))   AS BSNS_ENTY_SLR_KEY,
        CAST(IFF(LKP_BYR.BSNS_ENTY_KEY IS NULL, -2, LKP_BYR.BSNS_ENTY_KEY) AS NUMBER(10,0))   AS BSNS_ENTY_BYR_KEY,
        CAST(IFF(DQ.DERIVED_SAMPLED_RCPT_KEY IS NULL, -2, DQ.DERIVED_SAMPLED_RCPT_KEY) AS NUMBER(10,0)) AS SAMPLED_KEY,
        CAST(IFF(LKP_CD.CONTRACT_KEY IS NULL, -2, LKP_CD.CONTRACT_KEY) AS NUMBER(10,0))       AS CONTRACT_KEY,
        CAST(IFF(LKP_CS.CMDTY_SRC_KEY IS NULL, -2, LKP_CS.CMDTY_SRC_KEY) AS NUMBER(10,0))     AS CMDTY_SRC_KEY,
        CAST(IFF(LKP_CP.CNTRCT_PROD_KEY IS NULL, -2, LKP_CP.CNTRCT_PROD_KEY) AS NUMBER(10,0)) AS CNTRCT_PROD_KEY,
        CAST(DQ.PRCD_TONS_QY AS NUMBER(12,3))                                                 AS PRCD_TONS_QY,
        CAST(DQ.SHP_TONS_QY AS NUMBER(12,3))                                                  AS SHP_TONS_QY,
        CAST(DQ.UNLOADD_TONS_QY AS NUMBER(12,3))                                              AS UNLOADD_TONS_QY,
        CAST(DQ.FRZ_TRTMT_TONS_QY AS NUMBER(12,3))                                            AS FRZ_TRTMT_TONS_QY,
        CAST(DQ.DUST_TRTMT_TONS_QY AS NUMBER(12,3))                                           AS DUST_TRTMT_TONS_QY,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY AS NUMBER(12,3))                                        AS UNLOADD_SMPLD_TONS_QY,
        CAST(DQ.ASH_QLTY_PCT AS NUMBER(5,3))                                                  AS ASH_QLTY_PCT,
        CAST(DQ.SULFUR_QLTY_PCT AS NUMBER(5,3))                                               AS SULFUR_QLTY_PCT,
        CAST(DQ.MOISTURE_QLTY_PCT AS NUMBER(5,3))                                             AS MOISTURE_QLTY_PCT,
        CAST(DQ.BTU_PER_LB_MSR AS NUMBER(12,3))                                               AS BTU_PER_LB_MSR,
        CAST(DQ.SO2_LBS_PER_MBTU_MSR AS NUMBER(12,3))                                         AS SO2_LBS_PER_MBTU_MSR,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY * DQ.ASH_QLTY_PCT      AS NUMBER(12,5))                 AS UNLOADD_SMPLD_ASH_QY,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY * DQ.BTU_PER_LB_MSR    AS NUMBER(12,3))                 AS UNLOADD_SMPLD_BTU_LB_QY,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY * DQ.MOISTURE_QLTY_PCT AS NUMBER(12,5))                 AS UNLOADD_SMPLD_MOISTURE_QY,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY * DQ.SULFUR_QLTY_PCT   AS NUMBER(12,5))                 AS UNLOADD_SMPLD_SULFUR_QY,
        DQ.FDR_LAST_UPDT_TS,
        $V_SESSSTARTTIME                                                                      AS LAST_UPDT_TS
    FROM (
        SELECT
            SQ.RECEIPT_ID,
            SQ.CMDTY_SRC_ID,
            SQ.SHIPPED_TS,
            SQ.UNLOADD_TS,
            SQ.PRICED_DT,
            SQ.INVTRY_LOC_ID,
            SQ.CNTRCT_DTL_ID,
            SQ.PRCD_TONS_QY,
            SQ.SHP_TONS_QY,
            SQ.UNLOADD_TONS_QY,
            SQ.FRZ_TRTMT_TONS_QY,
            SQ.DUST_TRTMT_TONS_QY,
            SQ.UNLOADD_SMPLD_TONS_QY,
            SQ.ASH_QLTY_PCT,
            SQ.SULFUR_QLTY_PCT,
            SQ.MOISTURE_QLTY_PCT,
            SQ.BTU_PER_LB_MSR,
            SQ.SO2_LBS_PER_MBTU_MSR,
            SQ.LAST_UPDT_TS                                                                   AS FDR_LAST_UPDT_TS,
            UPPER(CASE WHEN LENGTH(LTRIM(RTRIM(SQ.CONTRACT_ID))) = 0 THEN ' ' ELSE RTRIM(SQ.CONTRACT_ID) END) AS O_CNTRCT_ID,
            IFF((SELECT MIN(SAMPLED_KEY) FROM feladm.FEL_SAMPLED_DIM
                  WHERE SMPLD_RSN_TX = CASE WHEN LENGTH(LTRIM(RTRIM(SQ.UNSMPLD_RSN_TX))) = 0 THEN ' ' ELSE RTRIM(SQ.UNSMPLD_RSN_TX) END) IS NULL,
                IFF(SQ.ASH_QLTY_PCT <> 0 OR SQ.SULFUR_QLTY_PCT <> 0
                 OR SQ.MOISTURE_QLTY_PCT <> 0 OR SQ.BTU_PER_LB_MSR <> 0,
                    (SELECT MIN(SAMPLED_KEY) FROM feladm.FEL_SAMPLED_DIM WHERE SMPLD_RSN_TX = 'Sampled'),
                    (SELECT MIN(SAMPLED_KEY) FROM feladm.FEL_SAMPLED_DIM WHERE SMPLD_RSN_TX = 'Unknown')),
                (SELECT MIN(SAMPLED_KEY) FROM feladm.FEL_SAMPLED_DIM
                  WHERE SMPLD_RSN_TX = CASE WHEN LENGTH(LTRIM(RTRIM(SQ.UNSMPLD_RSN_TX))) = 0 THEN ' ' ELSE RTRIM(SQ.UNSMPLD_RSN_TX) END)) AS DERIVED_SAMPLED_RCPT_KEY,
            (SELECT MIN(SYS_ID) FROM feladm.FEL_SYSTEM_DIM WHERE SYS_NM = 'COMTRAC')          AS V_SYS_ID
        FROM feladm.FEL_COAL_RCPTS_QTY_QLTY_FDR SQ
        WHERE UPPER(TRIM(SQ.STATUS_TX)) = $V_REC_STATUS
          AND $V_RUN_STATUS = 'C'
    ) DQ
    LEFT JOIN (
        SELECT RECEIPT_KEY, RECEIPT_ID
        FROM FELADM.FEL_RECEIPT_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY RECEIPT_ID ORDER BY RECEIPT_KEY) = 1
    ) LKP_RD
      ON LKP_RD.RECEIPT_ID = DQ.RECEIPT_ID
    LEFT JOIN (
        SELECT DATE_ID, FULL_DATE_DT
        FROM FELADM.AEP_DATE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY FULL_DATE_DT ORDER BY FULL_DATE_DT) = 1
    ) LKP_SHP
      ON LKP_SHP.FULL_DATE_DT = TRUNC(DQ.SHIPPED_TS, 'DD')
    LEFT JOIN (
        SELECT DATE_ID, FULL_DATE_DT
        FROM FELADM.AEP_DATE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY FULL_DATE_DT ORDER BY FULL_DATE_DT) = 1
    ) LKP_UNL
      ON LKP_UNL.FULL_DATE_DT = TRUNC(DQ.UNLOADD_TS, 'DD')
    LEFT JOIN (
        SELECT DATE_ID, FULL_DATE_DT
        FROM FELADM.AEP_DATE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY FULL_DATE_DT ORDER BY FULL_DATE_DT) = 1
    ) LKP_PRC
      ON LKP_PRC.FULL_DATE_DT = DQ.PRICED_DT
    LEFT JOIN (
        SELECT INVTRY_LOC_KEY, INVTRY_PRMRY_FCLTY_KEY, INVTRY_SCNDRY_FCLTY_KEY, INVTRY_LOC_ID
        FROM feladm.FEL_INVTRY_LOC_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY INVTRY_LOC_ID ORDER BY INVTRY_LOC_KEY) = 1
    ) LKP_IL
      ON LKP_IL.INVTRY_LOC_ID = DQ.INVTRY_LOC_ID
    LEFT JOIN (
        SELECT CNTRCT_PROD_KEY, CNTRCT_DTL_ID
        FROM feladm.FEL_CNTRCT_PROD_CD_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY CNTRCT_DTL_ID ORDER BY CNTRCT_PROD_KEY) = 1
    ) LKP_CP
      ON LKP_CP.CNTRCT_DTL_ID = DQ.CNTRCT_DTL_ID
    LEFT JOIN (
        SELECT ct.CURR_CNTRCT_VNDR_ID, ct.CURR_BYR_ID, UPPER(TRIM(ct.CONTRACT_ID)) AS CONTRACT_ID
        FROM feladm.FEL_COMTRAC_CONTRACT_FDR ct
        QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(ct.CONTRACT_ID)) ORDER BY ct.CURR_CNTRCT_VNDR_ID, ct.CURR_BYR_ID) = 1
    ) LKP_CF
      ON LKP_CF.CONTRACT_ID = DQ.O_CNTRCT_ID
    LEFT JOIN (
        SELECT cnt.CONTRACT_KEY, UPPER(TRIM(cnt.CONTRACT_ID)) AS CONTRACT_ID, UPPER(TRIM(cnt.SYSTEM_NM)) AS SYSTEM_NM
        FROM feladm.FEL_CONTRACT_DIM cnt
        QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(cnt.CONTRACT_ID)), UPPER(TRIM(cnt.SYSTEM_NM)) ORDER BY cnt.CONTRACT_KEY) = 1
    ) LKP_CD
      ON LKP_CD.CONTRACT_ID = DQ.O_CNTRCT_ID
     AND LKP_CD.SYSTEM_NM   = 'COMTRAC'
    LEFT JOIN (
        SELECT CMDTY_SRC_KEY, CMDTY_SRC_ID, CMDTY_SRC_EFCTV_DT, CMDTY_SRC_EXPR_DT
        FROM feladm.FEL_CMDTY_SRC_DIM
    ) LKP_CS
      ON LKP_CS.CMDTY_SRC_ID       = DQ.CMDTY_SRC_ID
     AND LKP_CS.CMDTY_SRC_EFCTV_DT <= TRUNC(DQ.UNLOADD_TS, 'DD')
     AND LKP_CS.CMDTY_SRC_EXPR_DT  >= TRUNC(DQ.UNLOADD_TS, 'DD')
    LEFT JOIN (
        SELECT BSNS_ENTY_KEY, BSNS_ENTY_ID, SYSTEM_ID
        FROM FELADM.FEL_BSNS_ENTY_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY BSNS_ENTY_ID, SYSTEM_ID ORDER BY BSNS_ENTY_KEY) = 1
    ) LKP_SLR
      ON LKP_SLR.BSNS_ENTY_ID = LKP_CF.CURR_CNTRCT_VNDR_ID
     AND LKP_SLR.SYSTEM_ID    = DQ.V_SYS_ID
    LEFT JOIN (
        SELECT BSNS_ENTY_KEY, BSNS_ENTY_ID, SYSTEM_ID
        FROM FELADM.FEL_BSNS_ENTY_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY BSNS_ENTY_ID, SYSTEM_ID ORDER BY BSNS_ENTY_KEY) = 1
    ) LKP_BYR
      ON LKP_BYR.BSNS_ENTY_ID = LKP_CF.CURR_BYR_ID
     AND LKP_BYR.SYSTEM_ID    = DQ.V_SYS_ID
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DQ.RECEIPT_ID ORDER BY LKP_CS.CMDTY_SRC_KEY) = 1
) SRC
WHERE TGT.RECEIPT_KEY = SRC.RECEIPT_KEY
  AND (   SRC.FDR_LAST_UPDT_TS >= $V_START_TIME
       OR NOT (    SRC.OWNING_FCLTY_KEY        = TGT.OWNING_FCLTY_KEY
               AND SRC.GEOG_FCLTY_KEY          = TGT.GEOG_FCLTY_KEY
               AND SRC.INVTRY_LOC_KEY          = TGT.INVTRY_LOC_KEY
               AND SRC.BSNS_ENTY_SLR_KEY       = TGT.BSNS_ENTY_SLR_KEY
               AND SRC.BSNS_ENTY_BYR_KEY       = TGT.BSNS_ENTY_BYR_KEY
               AND SRC.SAMPLED_KEY             = TGT.SAMPLED_KEY
               AND SRC.CONTRACT_KEY            = TGT.CONTRACT_KEY
               AND SRC.CNTRCT_PROD_KEY         = TGT.CNTRCT_PROD_KEY
               AND SRC.CMDTY_SRC_KEY           = TGT.CMDTY_SRC_KEY
               AND TGT.PRCD_TONS_QY            = SRC.PRCD_TONS_QY
               AND TGT.SHP_TONS_QY             = SRC.SHP_TONS_QY
               AND TGT.UNLOADD_TONS_QY         = SRC.UNLOADD_TONS_QY
               AND TGT.FRZ_TRTMT_TONS_QY       = SRC.FRZ_TRTMT_TONS_QY
               AND TGT.DUST_TRTMT_TONS_QY      = SRC.DUST_TRTMT_TONS_QY
               AND TGT.UNLOADD_SMPLD_TONS_QY   = SRC.UNLOADD_SMPLD_TONS_QY
               AND TGT.ASH_QLTY_PCT            = SRC.ASH_QLTY_PCT
               AND TGT.SULFUR_QLTY_PCT         = SRC.SULFUR_QLTY_PCT
               AND TGT.MOISTURE_QLTY_PCT       = SRC.MOISTURE_QLTY_PCT
               AND TGT.BTU_PER_LB_MSR          = SRC.BTU_PER_LB_MSR
               AND TGT.SO2_LBS_PER_MBTU_MSR    = SRC.SO2_LBS_PER_MBTU_MSR
               AND TGT.UNLOADD_SMPLD_ASH_QY    = SRC.UNLOADD_SMPLD_ASH_QY
               AND TGT.UNLOADD_SMPLD_BTU_LB_QY = SRC.UNLOADD_SMPLD_BTU_LB_QY));

INSERT INTO feladm.FEL_COAL_RCPTS_QTY_QLTY_FACT (
    RECEIPT_KEY,
    SHP_DT_ID,
    UNLOADD_DT_ID,
    PRCD_DT_ID,
    OWNING_FCLTY_KEY,
    GEOG_FCLTY_KEY,
    INVTRY_LOC_KEY,
    BSNS_ENTY_SLR_KEY,
    BSNS_ENTY_BYR_KEY,
    SAMPLED_KEY,
    CONTRACT_KEY,
    CMDTY_SRC_KEY,
    CNTRCT_PROD_KEY,
    PRCD_TONS_QY,
    SHP_TONS_QY,
    UNLOADD_TONS_QY,
    FRZ_TRTMT_TONS_QY,
    DUST_TRTMT_TONS_QY,
    UNLOADD_SMPLD_TONS_QY,
    ASH_QLTY_PCT,
    SULFUR_QLTY_PCT,
    MOISTURE_QLTY_PCT,
    BTU_PER_LB_MSR,
    SO2_LBS_PER_MBTU_MSR,
    UNLOADD_SMPLD_ASH_QY,
    UNLOADD_SMPLD_BTU_LB_QY,
    UNLOADD_SMPLD_MOISTURE_QY,
    UNLOADD_SMPLD_SULFUR_QY,
    LAST_UPDT_TS
)
SELECT
    SRC.RECEIPT_KEY,
    SRC.SHP_DT_ID,
    SRC.UNLOADD_DT_ID,
    SRC.PRCD_DT_ID,
    SRC.OWNING_FCLTY_KEY,
    SRC.GEOG_FCLTY_KEY,
    SRC.INVTRY_LOC_KEY,
    SRC.BSNS_ENTY_SLR_KEY,
    SRC.BSNS_ENTY_BYR_KEY,
    SRC.SAMPLED_KEY,
    SRC.CONTRACT_KEY,
    SRC.CMDTY_SRC_KEY,
    SRC.CNTRCT_PROD_KEY,
    SRC.PRCD_TONS_QY,
    SRC.SHP_TONS_QY,
    SRC.UNLOADD_TONS_QY,
    SRC.FRZ_TRTMT_TONS_QY,
    SRC.DUST_TRTMT_TONS_QY,
    SRC.UNLOADD_SMPLD_TONS_QY,
    SRC.ASH_QLTY_PCT,
    SRC.SULFUR_QLTY_PCT,
    SRC.MOISTURE_QLTY_PCT,
    SRC.BTU_PER_LB_MSR,
    SRC.SO2_LBS_PER_MBTU_MSR,
    SRC.UNLOADD_SMPLD_ASH_QY,
    SRC.UNLOADD_SMPLD_BTU_LB_QY,
    SRC.UNLOADD_SMPLD_MOISTURE_QY,
    SRC.UNLOADD_SMPLD_SULFUR_QY,
    SRC.LAST_UPDT_TS
FROM (
    SELECT
        CAST(LKP_RD.RECEIPT_KEY AS NUMBER(10,0))                                              AS RECEIPT_KEY,
        CAST(IFF(LKP_SHP.DATE_ID IS NULL, -2, LKP_SHP.DATE_ID) AS NUMBER(5,0))                AS SHP_DT_ID,
        CAST(IFF(LKP_UNL.DATE_ID IS NULL, -2, LKP_UNL.DATE_ID) AS NUMBER(5,0))                AS UNLOADD_DT_ID,
        CAST(IFF(LKP_PRC.DATE_ID IS NULL, -2, LKP_PRC.DATE_ID) AS NUMBER(5,0))                AS PRCD_DT_ID,
        CAST(IFF(LKP_IL.INVTRY_SCNDRY_FCLTY_KEY IS NULL, -2, LKP_IL.INVTRY_SCNDRY_FCLTY_KEY) AS NUMBER(10,0)) AS OWNING_FCLTY_KEY,
        CAST(IFF(LKP_IL.INVTRY_PRMRY_FCLTY_KEY IS NULL, -2, LKP_IL.INVTRY_PRMRY_FCLTY_KEY) AS NUMBER(10,0))   AS GEOG_FCLTY_KEY,
        CAST(IFF(LKP_IL.INVTRY_LOC_KEY IS NULL, -2, LKP_IL.INVTRY_LOC_KEY) AS NUMBER(10,0))   AS INVTRY_LOC_KEY,
        CAST(IFF(LKP_SLR.BSNS_ENTY_KEY IS NULL, -2, LKP_SLR.BSNS_ENTY_KEY) AS NUMBER(10,0))   AS BSNS_ENTY_SLR_KEY,
        CAST(IFF(LKP_BYR.BSNS_ENTY_KEY IS NULL, -2, LKP_BYR.BSNS_ENTY_KEY) AS NUMBER(10,0))   AS BSNS_ENTY_BYR_KEY,
        CAST(IFF(DQ.DERIVED_SAMPLED_RCPT_KEY IS NULL, -2, DQ.DERIVED_SAMPLED_RCPT_KEY) AS NUMBER(10,0)) AS SAMPLED_KEY,
        CAST(IFF(LKP_CD.CONTRACT_KEY IS NULL, -2, LKP_CD.CONTRACT_KEY) AS NUMBER(10,0))       AS CONTRACT_KEY,
        CAST(IFF(LKP_CS.CMDTY_SRC_KEY IS NULL, -2, LKP_CS.CMDTY_SRC_KEY) AS NUMBER(10,0))     AS CMDTY_SRC_KEY,
        CAST(IFF(LKP_CP.CNTRCT_PROD_KEY IS NULL, -2, LKP_CP.CNTRCT_PROD_KEY) AS NUMBER(10,0)) AS CNTRCT_PROD_KEY,
        CAST(DQ.PRCD_TONS_QY AS NUMBER(12,3))                                                 AS PRCD_TONS_QY,
        CAST(DQ.SHP_TONS_QY AS NUMBER(12,3))                                                  AS SHP_TONS_QY,
        CAST(DQ.UNLOADD_TONS_QY AS NUMBER(12,3))                                              AS UNLOADD_TONS_QY,
        CAST(DQ.FRZ_TRTMT_TONS_QY AS NUMBER(12,3))                                            AS FRZ_TRTMT_TONS_QY,
        CAST(DQ.DUST_TRTMT_TONS_QY AS NUMBER(12,3))                                           AS DUST_TRTMT_TONS_QY,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY AS NUMBER(12,3))                                        AS UNLOADD_SMPLD_TONS_QY,
        CAST(DQ.ASH_QLTY_PCT AS NUMBER(5,3))                                                  AS ASH_QLTY_PCT,
        CAST(DQ.SULFUR_QLTY_PCT AS NUMBER(5,3))                                               AS SULFUR_QLTY_PCT,
        CAST(DQ.MOISTURE_QLTY_PCT AS NUMBER(5,3))                                             AS MOISTURE_QLTY_PCT,
        CAST(DQ.BTU_PER_LB_MSR AS NUMBER(12,3))                                               AS BTU_PER_LB_MSR,
        CAST(DQ.SO2_LBS_PER_MBTU_MSR AS NUMBER(12,3))                                         AS SO2_LBS_PER_MBTU_MSR,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY * DQ.ASH_QLTY_PCT      AS NUMBER(12,5))                 AS UNLOADD_SMPLD_ASH_QY,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY * DQ.BTU_PER_LB_MSR    AS NUMBER(12,3))                 AS UNLOADD_SMPLD_BTU_LB_QY,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY * DQ.MOISTURE_QLTY_PCT AS NUMBER(12,5))                 AS UNLOADD_SMPLD_MOISTURE_QY,
        CAST(DQ.UNLOADD_SMPLD_TONS_QY * DQ.SULFUR_QLTY_PCT   AS NUMBER(12,5))                 AS UNLOADD_SMPLD_SULFUR_QY,
        $V_SESSSTARTTIME                                                                      AS LAST_UPDT_TS
    FROM (
        SELECT
            SQ.RECEIPT_ID,
            SQ.CMDTY_SRC_ID,
            SQ.SHIPPED_TS,
            SQ.UNLOADD_TS,
            SQ.PRICED_DT,
            SQ.INVTRY_LOC_ID,
            SQ.CNTRCT_DTL_ID,
            SQ.PRCD_TONS_QY,
            SQ.SHP_TONS_QY,
            SQ.UNLOADD_TONS_QY,
            SQ.FRZ_TRTMT_TONS_QY,
            SQ.DUST_TRTMT_TONS_QY,
            SQ.UNLOADD_SMPLD_TONS_QY,
            SQ.ASH_QLTY_PCT,
            SQ.SULFUR_QLTY_PCT,
            SQ.MOISTURE_QLTY_PCT,
            SQ.BTU_PER_LB_MSR,
            SQ.SO2_LBS_PER_MBTU_MSR,
            UPPER(CASE WHEN LENGTH(LTRIM(RTRIM(SQ.CONTRACT_ID))) = 0 THEN ' ' ELSE RTRIM(SQ.CONTRACT_ID) END) AS O_CNTRCT_ID,
            IFF((SELECT MIN(SAMPLED_KEY) FROM feladm.FEL_SAMPLED_DIM
                  WHERE SMPLD_RSN_TX = CASE WHEN LENGTH(LTRIM(RTRIM(SQ.UNSMPLD_RSN_TX))) = 0 THEN ' ' ELSE RTRIM(SQ.UNSMPLD_RSN_TX) END) IS NULL,
                IFF(SQ.ASH_QLTY_PCT <> 0 OR SQ.SULFUR_QLTY_PCT <> 0
                 OR SQ.MOISTURE_QLTY_PCT <> 0 OR SQ.BTU_PER_LB_MSR <> 0,
                    (SELECT MIN(SAMPLED_KEY) FROM feladm.FEL_SAMPLED_DIM WHERE SMPLD_RSN_TX = 'Sampled'),
                    (SELECT MIN(SAMPLED_KEY) FROM feladm.FEL_SAMPLED_DIM WHERE SMPLD_RSN_TX = 'Unknown')),
                (SELECT MIN(SAMPLED_KEY) FROM feladm.FEL_SAMPLED_DIM
                  WHERE SMPLD_RSN_TX = CASE WHEN LENGTH(LTRIM(RTRIM(SQ.UNSMPLD_RSN_TX))) = 0 THEN ' ' ELSE RTRIM(SQ.UNSMPLD_RSN_TX) END)) AS DERIVED_SAMPLED_RCPT_KEY,
            (SELECT MIN(SYS_ID) FROM feladm.FEL_SYSTEM_DIM WHERE SYS_NM = 'COMTRAC')          AS V_SYS_ID
        FROM feladm.FEL_COAL_RCPTS_QTY_QLTY_FDR SQ
        WHERE UPPER(TRIM(SQ.STATUS_TX)) = $V_REC_STATUS
          AND $V_RUN_STATUS = 'C'
    ) DQ
    LEFT JOIN (
        SELECT RECEIPT_KEY, RECEIPT_ID
        FROM FELADM.FEL_RECEIPT_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY RECEIPT_ID ORDER BY RECEIPT_KEY) = 1
    ) LKP_RD
      ON LKP_RD.RECEIPT_ID = DQ.RECEIPT_ID
    LEFT JOIN (
        SELECT DATE_ID, FULL_DATE_DT
        FROM FELADM.AEP_DATE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY FULL_DATE_DT ORDER BY FULL_DATE_DT) = 1
    ) LKP_SHP
      ON LKP_SHP.FULL_DATE_DT = TRUNC(DQ.SHIPPED_TS, 'DD')
    LEFT JOIN (
        SELECT DATE_ID, FULL_DATE_DT
        FROM FELADM.AEP_DATE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY FULL_DATE_DT ORDER BY FULL_DATE_DT) = 1
    ) LKP_UNL
      ON LKP_UNL.FULL_DATE_DT = TRUNC(DQ.UNLOADD_TS, 'DD')
    LEFT JOIN (
        SELECT DATE_ID, FULL_DATE_DT
        FROM FELADM.AEP_DATE
        QUALIFY ROW_NUMBER() OVER (PARTITION BY FULL_DATE_DT ORDER BY FULL_DATE_DT) = 1
    ) LKP_PRC
      ON LKP_PRC.FULL_DATE_DT = DQ.PRICED_DT
    LEFT JOIN (
        SELECT INVTRY_LOC_KEY, INVTRY_PRMRY_FCLTY_KEY, INVTRY_SCNDRY_FCLTY_KEY, INVTRY_LOC_ID
        FROM feladm.FEL_INVTRY_LOC_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY INVTRY_LOC_ID ORDER BY INVTRY_LOC_KEY) = 1
    ) LKP_IL
      ON LKP_IL.INVTRY_LOC_ID = DQ.INVTRY_LOC_ID
    LEFT JOIN (
        SELECT CNTRCT_PROD_KEY, CNTRCT_DTL_ID
        FROM feladm.FEL_CNTRCT_PROD_CD_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY CNTRCT_DTL_ID ORDER BY CNTRCT_PROD_KEY) = 1
    ) LKP_CP
      ON LKP_CP.CNTRCT_DTL_ID = DQ.CNTRCT_DTL_ID
    LEFT JOIN (
        SELECT ct.CURR_CNTRCT_VNDR_ID, ct.CURR_BYR_ID, UPPER(TRIM(ct.CONTRACT_ID)) AS CONTRACT_ID
        FROM feladm.FEL_COMTRAC_CONTRACT_FDR ct
        QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(ct.CONTRACT_ID)) ORDER BY ct.CURR_CNTRCT_VNDR_ID, ct.CURR_BYR_ID) = 1
    ) LKP_CF
      ON LKP_CF.CONTRACT_ID = DQ.O_CNTRCT_ID
    LEFT JOIN (
        SELECT cnt.CONTRACT_KEY, UPPER(TRIM(cnt.CONTRACT_ID)) AS CONTRACT_ID, UPPER(TRIM(cnt.SYSTEM_NM)) AS SYSTEM_NM
        FROM feladm.FEL_CONTRACT_DIM cnt
        QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(cnt.CONTRACT_ID)), UPPER(TRIM(cnt.SYSTEM_NM)) ORDER BY cnt.CONTRACT_KEY) = 1
    ) LKP_CD
      ON LKP_CD.CONTRACT_ID = DQ.O_CNTRCT_ID
     AND LKP_CD.SYSTEM_NM   = 'COMTRAC'
    LEFT JOIN (
        SELECT CMDTY_SRC_KEY, CMDTY_SRC_ID, CMDTY_SRC_EFCTV_DT, CMDTY_SRC_EXPR_DT
        FROM feladm.FEL_CMDTY_SRC_DIM
    ) LKP_CS
      ON LKP_CS.CMDTY_SRC_ID       = DQ.CMDTY_SRC_ID
     AND LKP_CS.CMDTY_SRC_EFCTV_DT <= TRUNC(DQ.UNLOADD_TS, 'DD')
     AND LKP_CS.CMDTY_SRC_EXPR_DT  >= TRUNC(DQ.UNLOADD_TS, 'DD')
    LEFT JOIN (
        SELECT BSNS_ENTY_KEY, BSNS_ENTY_ID, SYSTEM_ID
        FROM FELADM.FEL_BSNS_ENTY_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY BSNS_ENTY_ID, SYSTEM_ID ORDER BY BSNS_ENTY_KEY) = 1
    ) LKP_SLR
      ON LKP_SLR.BSNS_ENTY_ID = LKP_CF.CURR_CNTRCT_VNDR_ID
     AND LKP_SLR.SYSTEM_ID    = DQ.V_SYS_ID
    LEFT JOIN (
        SELECT BSNS_ENTY_KEY, BSNS_ENTY_ID, SYSTEM_ID
        FROM FELADM.FEL_BSNS_ENTY_DIM
        QUALIFY ROW_NUMBER() OVER (PARTITION BY BSNS_ENTY_ID, SYSTEM_ID ORDER BY BSNS_ENTY_KEY) = 1
    ) LKP_BYR
      ON LKP_BYR.BSNS_ENTY_ID = LKP_CF.CURR_BYR_ID
     AND LKP_BYR.SYSTEM_ID    = DQ.V_SYS_ID
    QUALIFY ROW_NUMBER() OVER (PARTITION BY DQ.RECEIPT_ID ORDER BY LKP_CS.CMDTY_SRC_KEY) = 1
) SRC
WHERE NOT EXISTS (
    SELECT 1
    FROM feladm.FEL_COAL_RCPTS_QTY_QLTY_FACT L
    WHERE L.RECEIPT_KEY = SRC.RECEIPT_KEY
);
