/*
================================================================================
 WORKFLOW  : wkf_FEL_COAL_DIM_LOAD
 SESSION   : s_m_FEL_CNTRCT_PROD_CD_DIM_ins_upd
 MAPPING   : m_FEL_CNTRCT_PROD_CD_DIM_ins_upd
 OPERATION : INSERT + UPDATE, data driven. RTR_INS_UPD splits on the dimension
             lookup alone; the unconnected DEFAULT1 group is discarded.
--------------------------------------------------------------------------------
 SOURCE    : GENDB01.FELADM.FEL_COMTRAC_CNTRCT_PROD_CD_FDR
 LOOKUPS   : GENDB01.FELADM.FEL_CONTRACT_DIM
             GENDB01.FELADM.FEL_SYSTEM_DIM
             GENDB01.FELADM.FEL_CNTRCT_PROD_CD_DIM
 TARGET    : GENDB01.FELADM.FEL_CNTRCT_PROD_CD_DIM   
             insert and update instances
--------------------------------------------------------------------------------
 PARAMETERS: $$START_TIME, $$RUN_STATUS (SQ filter), $$COMTRAC (system lookup)
             $$REC_STATUS is declared but not referenced
             SESSSTARTTIME -> LAST_UPDT_TS
             :UDF.DQ_FOR_CHAR_VARCHAR   empty or all-space to ' ', else right trim
 SQ OVERRIDE : none, source filter only:
                 LAST_UPDT_TS >= '$$START_TIME' AND '$$RUN_STATUS' = 'C'
 PRE-SQL   : none     POST-SQL : none     TRUNCATE TARGET : no
    $$START_TIME=1900/01/01 01:01:01
    $$REC_STATUS=ACTIVE
    $$RUN_STATUS=C
    $$COMTRAC=COMTRAC
    $$BUSINESSENTITY=BUSINESS ENTITY
    $$FACILITY=FACILITY
    $$INVTRYLOC=INVENTORY LOCATION
    $$GEN_UNIT=GENERATING UNIT

================================================================================
*/

SET V_START_TIME    = TO_TIMESTAMP_NTZ('2026-09-02 22:30:11', 'YYYY-MM-DD HH24:MI:SS');
SET V_RUN_STATUS    = 'C';
SET V_COMTRAC       = 'COMTRAC';
SET V_SESSSTARTTIME = CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ);

UPDATE GENDB01.FELADM.FEL_CNTRCT_PROD_CD_DIM TGT
SET
    CNTRCT_DTL_ID   = SRC.CNTRCT_DTL_ID,
    CONTRACT_KEY    = SRC.CONTRACT_KEY,
    PRODUCT_CD      = SRC.PRODUCT_CD,
    PRODUCT_NM      = SRC.PRODUCT_NM,
    PARNT_CNTRCT_NM = SRC.PARNT_CNTRCT_NM,
    CONTRACT_NM     = SRC.CONTRACT_NM,
    FOB_POINT_TX    = SRC.FOB_POINT_TX,
    SHP_MTHD_TX     = SRC.SHP_MTHD_TX,
    EFFECTIVE_DT    = SRC.EFFECTIVE_DT,
    EXPIRATION_DT   = SRC.EXPIRATION_DT,
    MODIFIED_DT     = SRC.MODIFIED_DT,
    LAST_UPDT_TS    = SRC.LAST_UPDT_TS
FROM (
    SELECT
        DQ.CNTRCT_DTL_ID,
        CAST(IFF(LKP_CD.CONTRACT_KEY IS NULL, -2, LKP_CD.CONTRACT_KEY) AS NUMBER(10,0))    AS CONTRACT_KEY,
        DQ.PRODUCT_CD,
        DQ.PRODUCT_NM,
        LEFT(IFF(LKP_CD.PARNT_CNTRCT_NM IS NULL, 'UNKNOWN', LKP_CD.PARNT_CNTRCT_NM), 40)   AS PARNT_CNTRCT_NM,
        LEFT(IFF(LKP_CD.CONTRACT_NM IS NULL, 'UNKNOWN', LKP_CD.CONTRACT_NM), 40)           AS CONTRACT_NM,
        DQ.FOB_POINT_TX,
        DQ.SHP_MTHD_TX,
        DQ.EFFECTIVE_DT,
        DQ.EXPIRATION_DT,
        DQ.MODIFIED_DT,
        $V_SESSSTARTTIME                                                                   AS LAST_UPDT_TS
    FROM (
        SELECT
            SQ.CNTRCT_DTL_ID,
            SQ.EFFECTIVE_DT,
            SQ.EXPIRATION_DT,
            SQ.MODIFIED_DT,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.CONTRACT_CD)))  = 0 THEN ' ' ELSE RTRIM(SQ.CONTRACT_CD)  END AS CONTRACT_CD,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.PRODUCT_CD)))   = 0 THEN ' ' ELSE RTRIM(SQ.PRODUCT_CD)   END AS PRODUCT_CD,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.PRODUCT_NM)))   = 0 THEN ' ' ELSE RTRIM(SQ.PRODUCT_NM)   END AS PRODUCT_NM,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.FOB_POINT_TX))) = 0 THEN ' ' ELSE RTRIM(SQ.FOB_POINT_TX) END AS FOB_POINT_TX,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.SHP_MTHD_TX)))  = 0 THEN ' ' ELSE RTRIM(SQ.SHP_MTHD_TX)  END AS SHP_MTHD_TX
        FROM GENDB01.FELADM.FEL_COMTRAC_CNTRCT_PROD_CD_FDR SQ
        WHERE SQ.LAST_UPDT_TS >= $V_START_TIME
          AND $V_RUN_STATUS = 'C'
    ) DQ
    LEFT JOIN (
        SELECT dim.CONTRACT_KEY, dim.PARNT_CNTRCT_NM, dim.CONTRACT_NM,
               TRIM(dim.CONTRACT_ID) AS CONTRACT_ID, dim.SYSTEM_ID
        FROM GENDB01.FELADM.FEL_CONTRACT_DIM dim
        QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(dim.CONTRACT_ID), dim.SYSTEM_ID ORDER BY dim.CONTRACT_KEY) = 1
    ) LKP_CD
      ON LKP_CD.CONTRACT_ID = DQ.CONTRACT_CD
     AND LKP_CD.SYSTEM_ID   = (SELECT MIN(SYS_ID) FROM GENDB01.FELADM.FEL_SYSTEM_DIM WHERE SYS_NM = $V_COMTRAC)
) SRC
WHERE TGT.CNTRCT_DTL_ID = SRC.CNTRCT_DTL_ID;

INSERT INTO GENDB01.FELADM.FEL_CNTRCT_PROD_CD_DIM (
    CNTRCT_PROD_KEY,
    CNTRCT_DTL_ID,
    CONTRACT_KEY,
    PRODUCT_CD,
    PRODUCT_NM,
    PARNT_CNTRCT_NM,
    CONTRACT_NM,
    FOB_POINT_TX,
    SHP_MTHD_TX,
    EFFECTIVE_DT,
    EXPIRATION_DT,
    MODIFIED_DT,
    LAST_UPDT_TS
)
SELECT
    SRC.CNTRCT_PROD_KEY,
    SRC.CNTRCT_DTL_ID,
    SRC.CONTRACT_KEY,
    SRC.PRODUCT_CD,
    SRC.PRODUCT_NM,
    SRC.PARNT_CNTRCT_NM,
    SRC.CONTRACT_NM,
    SRC.FOB_POINT_TX,
    SRC.SHP_MTHD_TX,
    SRC.EFFECTIVE_DT,
    SRC.EXPIRATION_DT,
    SRC.MODIFIED_DT,
    SRC.LAST_UPDT_TS
FROM (
    SELECT
        DQ.CNTRCT_DTL_ID,
        CAST(IFF(LKP_CD.CONTRACT_KEY IS NULL, -2, LKP_CD.CONTRACT_KEY) AS NUMBER(10,0))    AS CONTRACT_KEY,
        DQ.PRODUCT_CD,
        DQ.PRODUCT_NM,
        LEFT(IFF(LKP_CD.PARNT_CNTRCT_NM IS NULL, 'UNKNOWN', LKP_CD.PARNT_CNTRCT_NM), 40)   AS PARNT_CNTRCT_NM,
        LEFT(IFF(LKP_CD.CONTRACT_NM IS NULL, 'UNKNOWN', LKP_CD.CONTRACT_NM), 40)           AS CONTRACT_NM,
        DQ.FOB_POINT_TX,
        DQ.SHP_MTHD_TX,
        DQ.EFFECTIVE_DT,
        DQ.EXPIRATION_DT,
        DQ.MODIFIED_DT,
        $V_SESSSTARTTIME                                                                   AS LAST_UPDT_TS,
        NVL((SELECT MAX(CNTRCT_PROD_KEY) FROM GENDB01.FELADM.FEL_CNTRCT_PROD_CD_DIM), 0)
            + ROW_NUMBER() OVER (ORDER BY DQ.CNTRCT_DTL_ID)                                AS CNTRCT_PROD_KEY
    FROM (
        SELECT
            SQ.CNTRCT_DTL_ID,
            SQ.EFFECTIVE_DT,
            SQ.EXPIRATION_DT,
            SQ.MODIFIED_DT,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.CONTRACT_CD)))  = 0 THEN ' ' ELSE RTRIM(SQ.CONTRACT_CD)  END AS CONTRACT_CD,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.PRODUCT_CD)))   = 0 THEN ' ' ELSE RTRIM(SQ.PRODUCT_CD)   END AS PRODUCT_CD,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.PRODUCT_NM)))   = 0 THEN ' ' ELSE RTRIM(SQ.PRODUCT_NM)   END AS PRODUCT_NM,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.FOB_POINT_TX))) = 0 THEN ' ' ELSE RTRIM(SQ.FOB_POINT_TX) END AS FOB_POINT_TX,
            CASE WHEN LENGTH(LTRIM(RTRIM(SQ.SHP_MTHD_TX)))  = 0 THEN ' ' ELSE RTRIM(SQ.SHP_MTHD_TX)  END AS SHP_MTHD_TX
        FROM GENDB01.FELADM.FEL_COMTRAC_CNTRCT_PROD_CD_FDR SQ
        WHERE SQ.LAST_UPDT_TS >= $V_START_TIME
          AND $V_RUN_STATUS = 'C'
    ) DQ
    LEFT JOIN (
        SELECT dim.CONTRACT_KEY, dim.PARNT_CNTRCT_NM, dim.CONTRACT_NM,
               TRIM(dim.CONTRACT_ID) AS CONTRACT_ID, dim.SYSTEM_ID
        FROM GENDB01.FELADM.FEL_CONTRACT_DIM dim
        QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(dim.CONTRACT_ID), dim.SYSTEM_ID ORDER BY dim.CONTRACT_KEY) = 1
    ) LKP_CD
      ON LKP_CD.CONTRACT_ID = DQ.CONTRACT_CD
     AND LKP_CD.SYSTEM_ID   = (SELECT MIN(SYS_ID) FROM GENDB01.FELADM.FEL_SYSTEM_DIM WHERE SYS_NM = $V_COMTRAC)
) SRC
WHERE NOT EXISTS (
    SELECT 1
    FROM GENDB01.FELADM.FEL_CNTRCT_PROD_CD_DIM L
    WHERE L.CNTRCT_DTL_ID = SRC.CNTRCT_DTL_ID
);
