/*
================================================================================
 WORKFLOW  : wkf_FEL_COAL_DIM_LOAD
 SESSION   : s_m_FEL_TRAN_CLASS_DIM
 MAPPING   : m_FEL_TRAN_CLASS_DIM_ins_upd
 OPERATION : INSERT + UPDATE, data driven. RTRTRANS splits on the dimension
             lookup; the unconnected DEFAULT1 group is discarded.
--------------------------------------------------------------------------------
 SOURCE    : GENDB01.FELADM.FEL_FV_TRANS_FDR

 LOOKUPS   : GENDB01.FELADM.FEL_SYSTEM_DIM
             GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
             GENDB01.FELADM.FEL_TRAN_CLASS_DIM

 TARGET    : GENDB01.FELADM.FEL_TRAN_CLASS_DIM
--------------------------------------------------------------------------------
 PARAMETERS: none declared on the mapping
             SESSSTARTTIME -> LAST_UPDT_TS
             EXP_DEFAULT_VALUES locals: v_fake_val -999, v_next_val a row counter,
             v_lkp_Max_Key the unconnected max key lookup
 SQ OVERRIDE : PRESENT, SELECT DISTINCT of the five level names from the feeder
 PRE-SQL   : none     POST-SQL : none     TRUNCATE TARGET : no

[FEL.WF:wkf_FEL_COAL_DIM_LOAD]
$$START_TIME=2026-09-05 22:30:12
$$REC_STATUS=ACTIVE
$$RUN_STATUS=C
$$COMTRAC=COMTRAC
$$BUSINESSENTITY=BUSINESS ENTITY
$$FACILITY=FACILITY
$$INVTRYLOC=INVENTORY LOCATION
$$GEN_UNIT=GENERATING UNIT
$DBConnection_Target=fel_GENDB001
$DBConnection_Source=fel_GENDB001
================================================================================
*/

SET V_SESSSTARTTIME = CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ);

UPDATE GENDB01.FELADM.FEL_TRAN_CLASS_DIM TGT
SET
    TRAN_CLS_LVL_4_NM  = SRC.TRAN_CLS_LVL_4_NM,
    TRAN_CLS_LVL_4_RNK = SRC.TRAN_CLS_LVL_4_RNK,
    TRAN_CLS_LVL_1_NM  = SRC.TRAN_CLS_LVL_1_NM,
    TRAN_CLS_LVL_1_RNK = SRC.TRAN_CLS_LVL_1_RNK,
    TRAN_CLS_LVL_2_NM  = SRC.TRAN_CLS_LVL_2_NM,
    TRAN_CLS_LVL_2_RNK = SRC.TRAN_CLS_LVL_2_RNK,
    TRAN_CLS_LVL_3_NM  = SRC.TRAN_CLS_LVL_3_NM,
    TRAN_CLS_LVL_3_RNK = SRC.TRAN_CLS_LVL_3_RNK,
    TRAN_CLS_LVL_5_NM  = SRC.TRAN_CLS_LVL_5_NM,
    TRAN_CLS_LVL_5_RNK = SRC.TRAN_CLS_LVL_5_RNK,
    SYSTEM_ID          = SRC.SYSTEM_ID,
    LAST_UPDT_TS       = SRC.LAST_UPDT_TS
FROM (
    SELECT
        LEFT(SQ.TRAN_CLS_LVL_1_NM, 16)                                          AS TRAN_CLS_LVL_1_NM,
        LEFT(SQ.TRAN_CLS_LVL_2_NM, 8)                                           AS TRAN_CLS_LVL_2_NM,
        SQ.TRAN_CLS_LVL_3_NM,
        SQ.TRAN_CLS_LVL_4_NM,
        SQ.TRAN_CLS_LVL_5_NM,
        LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLS_LVL_1_NM, 16))))                     AS U1,
        LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLS_LVL_2_NM, 8))))                      AS U2,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_3_NM)))                               AS U3,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_4_NM)))                               AS U4,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_5_NM)))                               AS U5,
        CAST(NVL(X1.TRAN_CLS_RNK, NVL(M1.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_1_RNK,
        CAST(NVL(X2.TRAN_CLS_RNK, NVL(M2.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_2_RNK,
        CAST(NVL(X3.TRAN_CLS_RNK, NVL(M3.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_3_RNK,
        CAST(NVL(X4.TRAN_CLS_RNK, NVL(M4.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_4_RNK,
        CAST(NVL(X5.TRAN_CLS_RNK, NVL(M5.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_5_RNK,
        CAST((SELECT MIN(SYS_ID) FROM GENDB01.FELADM.FEL_SYSTEM_DIM WHERE SYS_NM = 'COMTRAC') AS NUMBER(5,0)) AS SYSTEM_ID,
        $V_SESSSTARTTIME                                                        AS LAST_UPDT_TS
    FROM (
        SELECT DISTINCT
            F.TRAN_CLS_LVL_1_NM,
            F.TRAN_CLS_LVL_2_NM,
            F.TRAN_CLS_LVL_3_NM,
            F.TRAN_CLS_LVL_4_NM,
            F.TRAN_CLS_LVL_5_NM
        FROM GENDB01.FELADM.FEL_FV_TRANS_FDR F
    ) SQ
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X1
      ON X1.TRAN_CLS_LVL_RNK = 1 AND X1.LBL = LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLS_LVL_1_NM, 16))))
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X2
      ON X2.TRAN_CLS_LVL_RNK = 2 AND X2.LBL = LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLS_LVL_2_NM, 8))))
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X3
      ON X3.TRAN_CLS_LVL_RNK = 3 AND X3.LBL = LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_3_NM)))
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X4
      ON X4.TRAN_CLS_LVL_RNK = 4 AND X4.LBL = LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_4_NM)))
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X5
      ON X5.TRAN_CLS_LVL_RNK = 5 AND X5.LBL = LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_5_NM)))
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M1 ON M1.TRAN_CLS_LVL_RNK = 1
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M2 ON M2.TRAN_CLS_LVL_RNK = 2
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M3 ON M3.TRAN_CLS_LVL_RNK = 3
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M4 ON M4.TRAN_CLS_LVL_RNK = 4
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M5 ON M5.TRAN_CLS_LVL_RNK = 5
) SRC
WHERE TRIM(UPPER(TGT.TRAN_CLS_LVL_1_NM)) = SRC.U1
  AND TRIM(UPPER(TGT.TRAN_CLS_LVL_2_NM)) = SRC.U2
  AND TRIM(UPPER(TGT.TRAN_CLS_LVL_3_NM)) = SRC.U3
  AND TRIM(UPPER(TGT.TRAN_CLS_LVL_4_NM)) = SRC.U4
  AND TRIM(UPPER(TGT.TRAN_CLS_LVL_5_NM)) = SRC.U5
  AND TGT.SYSTEM_ID = SRC.SYSTEM_ID
  AND (   TGT.TRAN_CLS_LVL_1_RNK <> SRC.TRAN_CLS_LVL_1_RNK
       OR TGT.TRAN_CLS_LVL_2_RNK <> SRC.TRAN_CLS_LVL_2_RNK
       OR TGT.TRAN_CLS_LVL_3_RNK <> SRC.TRAN_CLS_LVL_3_RNK
       OR TGT.TRAN_CLS_LVL_4_RNK <> SRC.TRAN_CLS_LVL_4_RNK
       OR TGT.TRAN_CLS_LVL_5_RNK <> SRC.TRAN_CLS_LVL_5_RNK);

INSERT INTO GENDB01.FELADM.FEL_TRAN_CLASS_DIM (
    TRAN_CLS_KEY,
    TRAN_CLS_LVL_4_NM,
    TRAN_CLS_LVL_4_RNK,
    TRAN_CLS_LVL_1_NM,
    TRAN_CLS_LVL_1_RNK,
    TRAN_CLS_LVL_2_NM,
    TRAN_CLS_LVL_2_RNK,
    TRAN_CLS_LVL_3_NM,
    TRAN_CLS_LVL_3_RNK,
    TRAN_CLS_LVL_5_NM,
    TRAN_CLS_LVL_5_RNK,
    SYSTEM_ID,
    LAST_UPDT_TS
)
SELECT
    SRC.TRAN_CLS_KEY,
    SRC.TRAN_CLS_LVL_4_NM,
    SRC.TRAN_CLS_LVL_4_RNK,
    SRC.TRAN_CLS_LVL_1_NM,
    SRC.TRAN_CLS_LVL_1_RNK,
    SRC.TRAN_CLS_LVL_2_NM,
    SRC.TRAN_CLS_LVL_2_RNK,
    SRC.TRAN_CLS_LVL_3_NM,
    SRC.TRAN_CLS_LVL_3_RNK,
    SRC.TRAN_CLS_LVL_5_NM,
    SRC.TRAN_CLS_LVL_5_RNK,
    SRC.SYSTEM_ID,
    SRC.LAST_UPDT_TS
FROM (
    SELECT
        LEFT(SQ.TRAN_CLS_LVL_1_NM, 16)                                          AS TRAN_CLS_LVL_1_NM,
        LEFT(SQ.TRAN_CLS_LVL_2_NM, 8)                                           AS TRAN_CLS_LVL_2_NM,
        SQ.TRAN_CLS_LVL_3_NM,
        SQ.TRAN_CLS_LVL_4_NM,
        SQ.TRAN_CLS_LVL_5_NM,
        LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLS_LVL_1_NM, 16))))                     AS U1,
        LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLS_LVL_2_NM, 8))))                      AS U2,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_3_NM)))                               AS U3,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_4_NM)))                               AS U4,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_5_NM)))                               AS U5,
        CAST(NVL(X1.TRAN_CLS_RNK, NVL(M1.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_1_RNK,
        CAST(NVL(X2.TRAN_CLS_RNK, NVL(M2.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_2_RNK,
        CAST(NVL(X3.TRAN_CLS_RNK, NVL(M3.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_3_RNK,
        CAST(NVL(X4.TRAN_CLS_RNK, NVL(M4.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_4_RNK,
        CAST(NVL(X5.TRAN_CLS_RNK, NVL(M5.MAX_RNK, 1)) AS NUMBER(10,0))          AS TRAN_CLS_LVL_5_RNK,
        CAST((SELECT MIN(SYS_ID) FROM GENDB01.FELADM.FEL_SYSTEM_DIM WHERE SYS_NM = 'COMTRAC') AS NUMBER(5,0)) AS SYSTEM_ID,
        $V_SESSSTARTTIME                                                        AS LAST_UPDT_TS,
        NVL((SELECT MAX(TRAN_CLS_KEY) FROM GENDB01.FELADM.FEL_TRAN_CLASS_DIM), 0)
            + ROW_NUMBER() OVER (ORDER BY SQ.TRAN_CLS_LVL_1_NM, SQ.TRAN_CLS_LVL_2_NM,
                                          SQ.TRAN_CLS_LVL_3_NM, SQ.TRAN_CLS_LVL_4_NM,
                                          SQ.TRAN_CLS_LVL_5_NM)                 AS TRAN_CLS_KEY
    FROM (
        SELECT DISTINCT
            F.TRAN_CLS_LVL_1_NM,
            F.TRAN_CLS_LVL_2_NM,
            F.TRAN_CLS_LVL_3_NM,
            F.TRAN_CLS_LVL_4_NM,
            F.TRAN_CLS_LVL_5_NM
        FROM GENDB01.FELADM.FEL_FV_TRANS_FDR F
    ) SQ
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X1
      ON X1.TRAN_CLS_LVL_RNK = 1 AND X1.LBL = LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLS_LVL_1_NM, 16))))
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X2
      ON X2.TRAN_CLS_LVL_RNK = 2 AND X2.LBL = LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLS_LVL_2_NM, 8))))
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X3
      ON X3.TRAN_CLS_LVL_RNK = 3 AND X3.LBL = LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_3_NM)))
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X4
      ON X4.TRAN_CLS_LVL_RNK = 4 AND X4.LBL = LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_4_NM)))
    LEFT JOIN (SELECT TRAN_CLS_RNK, TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) AS LBL
               FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF
               QUALIFY ROW_NUMBER() OVER (PARTITION BY TRAN_CLS_LVL_RNK, TRIM(UPPER(TRAN_CLS_LBL_TX)) ORDER BY TRAN_CLS_RNK) = 1) X5
      ON X5.TRAN_CLS_LVL_RNK = 5 AND X5.LBL = LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL_5_NM)))
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M1 ON M1.TRAN_CLS_LVL_RNK = 1
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M2 ON M2.TRAN_CLS_LVL_RNK = 2
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M3 ON M3.TRAN_CLS_LVL_RNK = 3
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M4 ON M4.TRAN_CLS_LVL_RNK = 4
    LEFT JOIN (SELECT MAX(TRAN_CLS_RNK) AS MAX_RNK, TRAN_CLS_LVL_RNK FROM GENDB01.FELADM.FEL_TRAN_CLS_ORDER_XRF GROUP BY TRAN_CLS_LVL_RNK) M5 ON M5.TRAN_CLS_LVL_RNK = 5
) SRC
WHERE NOT EXISTS (
    SELECT 1
    FROM GENDB01.FELADM.FEL_TRAN_CLASS_DIM CLS
    WHERE TRIM(UPPER(CLS.TRAN_CLS_LVL_1_NM)) = SRC.U1
      AND TRIM(UPPER(CLS.TRAN_CLS_LVL_2_NM)) = SRC.U2
      AND TRIM(UPPER(CLS.TRAN_CLS_LVL_3_NM)) = SRC.U3
      AND TRIM(UPPER(CLS.TRAN_CLS_LVL_4_NM)) = SRC.U4
      AND TRIM(UPPER(CLS.TRAN_CLS_LVL_5_NM)) = SRC.U5
      AND CLS.SYSTEM_ID = SRC.SYSTEM_ID
);
