/*
================================================================================
 WORKFLOW  : wkf_FEL_COAL_FACT_LOAD
 SESSION   : s_m_FEL_FV_TRAN_FACT_ins
 MAPPING   : m_FEL_FV_TRAN_FACT_ins
 OPERATION : TRUNCATE + INSERT, full reload. No router, no update strategy.
             SEQTRANS supplies the surrogate key.
--------------------------------------------------------------------------------
 SOURCE    : AEP_DW_FV_TRANS_VW   full read, no filter
 LOOKUPS   : 21, all Use Any Value on multiple match: the FEL system, month,
             date, transaction class, account type, inventory location,
             accounting location, contract, contract product, generating unit,
             facility and business entity dimensions, plus nine PeopleSoft ones
             whose SQL overrides upper case and trim the matched column.
 TARGET    : feladm.FEL_FV_TRAN_FACT
--------------------------------------------------------------------------------
 PARAMETERS: none declared on the mapping
             SESSSTARTTIME -> LAST_UPDT_TS
 SQ OVERRIDE : none, and no source filter, so the reader takes the whole view
 PRE-SQL   : none     POST-SQL : none     TRUNCATE TARGET : YES
--------------------------------------------------------------------------------
 NOTES     : SEQTRANS is Reset YES, so each run numbers its rows from 1 in source
             read order, which no ORDER BY pins down; a deterministic one is used.
             Keys give -2 when the driving source value is null and -1 when it is
             present but not found, except transaction class which is always -2.
             Text uses 'UNKNOWN' and 'INVALID', the sub category '-2' and '-1'.
             Kept as authored: the resource type lookup is called with the
             constant 'UNKWN' and ignores CF_COST_COMP; the work order lookup
             matches CF_WORK_ORDER against ACTIVITY_ID with PRIMARY_SOURCE_CD
             pinned to 'EPM'; o_PCBU_ID is a 5 character port, so its defaults
             reach the target cut to 'UNKNO' and 'INVAL'.
             The captured run loaded 2138256 rows.
================================================================================
*/

SET V_SESSSTARTTIME = CAST(CURRENT_TIMESTAMP() AS TIMESTAMP_NTZ);

TRUNCATE TABLE feladm.FEL_FV_TRAN_FACT;

INSERT INTO feladm.FEL_FV_TRAN_FACT (
    FNCL_VIEW_TRAN_KEY,
    TRAN_ID,
    SYSTEM_ID,
    ACCTG_MO_DAY_ID,
    CAL_DAY_ID,
    TRAN_CLS_KEY,
    OWNING_FCLTY_KEY,
    GEOG_FCLTY_KEY,
    BSNS_ENTY_KEY,
    JO_BSNS_ENTY_KEY,
    ACCTG_INVTRY_LOC_KEY,
    INVTRY_LOC_KEY,
    UNIT_KEY,
    CONTRACT_KEY,
    CNTRCT_PROD_KEY,
    ACCT_TYP_KEY,
    ACCOUNT_CD,
    PROJ_CST_BSNS_UNT_ID,
    EPM_DEPT_ID,
    EPM_ABM_ACTV_ID,
    EPM_BSNS_UNT_GL_ID,
    EPM_RSRC_TYP_ID,
    EPM_PROJ_ID,
    WO_ID,
    RSRC_SBCTGY_CD,
    ENTRY_ID,
    RECEIPT_ID,
    RECLAIM_ID,
    TRANSACTION_QY,
    TRANSACTION_AT,
    DELETE_FL,
    LAST_UPDT_TS
)
SELECT
    ROW_NUMBER() OVER (ORDER BY SRC.FATRAN_ID, SRC.FAENTRY_ID)                              AS FNCL_VIEW_TRAN_KEY,
    CAST(IFF(SRC.FATRAN_ID IS NULL, -2, SRC.FATRAN_ID) AS NUMBER(10,0))                     AS TRAN_ID,
    CAST(SRC.V_SYSTEM_ID AS NUMBER(5,0))                                                    AS SYSTEM_ID,
    CAST(IFF(LKP_MO.ACCTG_MO_DAY_ID IS NOT NULL, LKP_MO.ACCTG_MO_DAY_ID,
             IFF(SRC.ACCT_YEAR_MONTH_DAY IS NULL, -2, -1)) AS NUMBER(5,0))                  AS ACCTG_MO_DAY_ID,
    CAST(IFF(LKP_DT.DATE_ID IS NOT NULL, LKP_DT.DATE_ID,
             IFF(SRC.TRANSACTION_DATE IS NULL, -2, -1)) AS NUMBER(5,0))                     AS CAL_DAY_ID,
    CAST(IFF(LKP_TC.TRAN_CLS_KEY IS NOT NULL, LKP_TC.TRAN_CLS_KEY, -2) AS NUMBER(10,0))     AS TRAN_CLS_KEY,
    CAST(IFF(LKP_IL.INVTRY_SCNDRY_FCLTY_KEY IS NOT NULL, LKP_IL.INVTRY_SCNDRY_FCLTY_KEY,
             IFF(SRC.INV_LOC_ID IS NULL, -2, -1)) AS NUMBER(10,0))                          AS OWNING_FCLTY_KEY,
    CAST(IFF(LKP_IL.INVTRY_PRMRY_FCLTY_KEY IS NOT NULL, LKP_IL.INVTRY_PRMRY_FCLTY_KEY,
             IFF(SRC.INV_LOC_ID IS NULL, -2, -1)) AS NUMBER(10,0))                          AS GEOG_FCLTY_KEY,
    CAST(IFF(LKP_FAC.BSNS_ENTY_KEY IS NOT NULL, LKP_FAC.BSNS_ENTY_KEY,
             IFF(SRC.INV_LOC_ID IS NULL, -2, -1)) AS NUMBER(10,0))                          AS BSNS_ENTY_KEY,
    CAST(IFF(LKP_JOBE.BSNS_ENTY_KEY IS NOT NULL, LKP_JOBE.BSNS_ENTY_KEY,
             IFF(SRC.JO_BSNS_ENTY_ID IS NULL, -2, -1)) AS NUMBER(10,0))                     AS JO_BSNS_ENTY_KEY,
    CAST(IFF(LKP_AL.ACCTG_INVTRY_LOC_KEY IS NOT NULL, LKP_AL.ACCTG_INVTRY_LOC_KEY,
             IFF(SRC.O_ACCT_INV_LOC_NM IS NULL, -2, -1)) AS NUMBER(10,0))                   AS ACCTG_INVTRY_LOC_KEY,
    CAST(IFF(LKP_IL.INVTRY_LOC_KEY IS NOT NULL, LKP_IL.INVTRY_LOC_KEY,
             IFF(SRC.INV_LOC_ID IS NULL, -2, -1)) AS NUMBER(10,0))                          AS INVTRY_LOC_KEY,
    CAST(IFF(LKP_GU.UNIT_KEY IS NOT NULL, LKP_GU.UNIT_KEY,
             IFF(SRC.GEN_UNIT_ID IS NULL, -2, -1)) AS NUMBER(10,0))                         AS UNIT_KEY,
    CAST(IFF(LKP_CN.CONTRACT_KEY IS NOT NULL, LKP_CN.CONTRACT_KEY,
             IFF(SRC.O_CNTRCT_ID IS NULL, -2, -1)) AS NUMBER(10,0))                         AS CONTRACT_KEY,
    CAST(IFF(LKP_CP.CNTRCT_PROD_KEY IS NOT NULL, LKP_CP.CNTRCT_PROD_KEY,
             IFF(SRC.CNTRCTDTL_ID IS NULL, -2, -1)) AS NUMBER(10,0))                        AS CNTRCT_PROD_KEY,
    CAST(IFF(LKP_AT.ACCT_TYP_KEY IS NOT NULL, LKP_AT.ACCT_TYP_KEY,
             IFF(SRC.O_ACCTTYPECLASSNAME IS NULL, -2, -1)) AS NUMBER(10,0))                 AS ACCT_TYP_KEY,
    LEFT(IFF(LKP_GL.ACCOUNT IS NOT NULL, LKP_GL.ACCOUNT,
             IFF(SRC.CF_GL_ACCT IS NULL, 'UNKNOWN', 'INVALID')), 10)                        AS ACCOUNT_CD,
    LEFT(IFF(LKP_PCBU.BUSINESS_UNIT_PC IS NOT NULL, LKP_PCBU.BUSINESS_UNIT_PC,
             IFF(SRC.CF_PROJ_COST_BU IS NULL, 'UNKNOWN', 'INVALID')), 5)                    AS PROJ_CST_BSNS_UNT_ID,
    CAST(IFF(LKP_DEPT.EPM_DEPT_ID IS NOT NULL, LKP_DEPT.EPM_DEPT_ID,
             IFF(SRC.CF_DEPT IS NULL, -2, -1)) AS NUMBER(10,0))                             AS EPM_DEPT_ID,
    CAST(IFF(LKP_ABM.EPM_ABM_ACTV_ID IS NOT NULL, LKP_ABM.EPM_ABM_ACTV_ID,
             IFF(SRC.CF_ABM_ACTIVITY IS NULL, -2, -1)) AS NUMBER(10,0))                     AS EPM_ABM_ACTV_ID,
    CAST(IFF(LKP_RC.EPM_BUS_UNIT_GL_ID IS NOT NULL, LKP_RC.EPM_BUS_UNIT_GL_ID,
             IFF(SRC.CF_GL_BUS_UNIT IS NULL, -2, -1)) AS NUMBER(10,0))                      AS EPM_BSNS_UNT_GL_ID,
    CAST(IFF(LKP_CC.EPM_RSRC_TYPE_ID IS NOT NULL, LKP_CC.EPM_RSRC_TYPE_ID,
             IFF(SRC.CF_COST_COMP IS NULL, -2, -1)) AS NUMBER(10,0))                        AS EPM_RSRC_TYP_ID,
    CAST(IFF(LKP_PROJ.EPM_PROJECT_ID IS NOT NULL, LKP_PROJ.EPM_PROJECT_ID,
             IFF(SRC.CF_PROJECT IS NULL, -2, -1)) AS NUMBER(10,0))                          AS EPM_PROJ_ID,
    LEFT(TO_VARCHAR(CAST(IFF(LKP_WO.WORK_ORDER_ID IS NOT NULL, LKP_WO.WORK_ORDER_ID,
             IFF(SRC.CF_WORK_ORDER IS NULL AND SRC.CF_PROJECT IS NULL
                 AND SRC.CF_PROJ_COST_BU IS NULL, -2, -1)) AS NUMBER(10,0))), 10)           AS WO_ID,
    LEFT(IFF(LKP_RSC.RESOURCE_SUB_CAT IS NOT NULL, LKP_RSC.RESOURCE_SUB_CAT,
             IFF(SRC.CF_RESOURCE_CAT IS NULL, '-2', '-1')), 5)                              AS RSRC_SBCTGY_CD,
    CAST(IFF(SRC.FAENTRY_ID IS NULL, -2, SRC.FAENTRY_ID) AS NUMBER(10,0))                   AS ENTRY_ID,
    CAST(IFF(SRC.RECEIPT_ID IS NULL, -2, SRC.RECEIPT_ID) AS NUMBER(10,0))                   AS RECEIPT_ID,
    CAST(IFF(SRC.RECLAIM_ID IS NULL, -2, SRC.RECLAIM_ID) AS NUMBER(10,0))                   AS RECLAIM_ID,
    CAST(SRC.QTY AS NUMBER(18,9))                                                           AS TRANSACTION_QY,
    CAST(SRC.AMT AS NUMBER(18,9))                                                           AS TRANSACTION_AT,
    'N'                                                                                     AS DELETE_FL,
    $V_SESSSTARTTIME                                                                        AS LAST_UPDT_TS
FROM (
    SELECT
        SQ.ACCT_YEAR_MONTH_DAY,
        SQ.TRANSACTION_DATE,
        SQ.FAENTRY_ID,
        SQ.FATRAN_ID,
        SQ.INV_LOC_ID,
        SQ.GEN_UNIT_ID,
        SQ.CNTRCTDTL_ID,
        SQ.CF_GL_ACCT,
        SQ.CF_DEPT,
        SQ.CF_WORK_ORDER,
        SQ.CF_COST_COMP,
        SQ.CF_PROJ_COST_BU,
        SQ.CF_RESOURCE_CAT,
        SQ.CF_ABM_ACTIVITY,
        SQ.CF_PROJECT,
        SQ.CF_GL_BUS_UNIT,
        SQ.QTY,
        SQ.AMT,
        SQ.RECLAIM_ID,
        SQ.RECEIPT_ID,
        SQ.JO_BSNS_ENTY_ID,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLS_LVL1_NM)))                                            AS O_TRAN_CLASS_LVL1,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLASS_LVL2_NM)))                                          AS O_TRAN_CLASS_LVL2,
        LTRIM(RTRIM(UPPER(LEFT(SQ.TRAN_CLASS_LVL3_NM, 20))))                                AS O_TRAN_CLASS_LVL3,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLASS_LVL4_NM)))                                          AS O_TRAN_CLASS_LVL4,
        LTRIM(RTRIM(UPPER(SQ.TRAN_CLASS_LVL5_NM)))                                          AS O_TRAN_CLASS_LVL5,
        UPPER(LTRIM(RTRIM(SQ.ACCTTYPECLASSNAME)))                                           AS O_ACCTTYPECLASSNAME,
        LTRIM(RTRIM(UPPER(SQ.ACCT_INV_LOC_NM)))                                             AS O_ACCT_INV_LOC_NM,
        LEFT(LTRIM(RTRIM(TO_VARCHAR(CAST(SQ.GEN_UNIT_ID AS NUMBER(15,0))))), 25)            AS O_GEN_UNIT_ID,
        LTRIM(RTRIM(SQ.CNTRCT_ID))                                                          AS O_CNTRCT_ID,
        (SELECT MIN(SYS_ID) FROM feladm.FEL_SYSTEM_DIM WHERE SYS_NM = 'COMTRAC')            AS V_SYSTEM_ID
    FROM AEP_DW_FV_TRANS_VW SQ
) SRC
LEFT JOIN (
    SELECT ACCTG_MO_DAY_ID, MONTH_NB, CALENDAR_YEAR
    FROM feladm.FEL_ACCTG_MONTH_VW
    QUALIFY ROW_NUMBER() OVER (PARTITION BY MONTH_NB, CALENDAR_YEAR ORDER BY MONTH_NB, CALENDAR_YEAR) = 1
) LKP_MO
  ON LKP_MO.MONTH_NB      = CAST(DATE_PART(MONTH, SRC.ACCT_YEAR_MONTH_DAY) AS NUMBER(10,0))
 AND LKP_MO.CALENDAR_YEAR = CAST(DATE_PART(YEAR,  SRC.ACCT_YEAR_MONTH_DAY) AS NUMBER(10,0))
LEFT JOIN (
    SELECT DATE_ID, FULL_DATE_DT
    FROM FELADM.AEP_DATE
    QUALIFY ROW_NUMBER() OVER (PARTITION BY FULL_DATE_DT ORDER BY FULL_DATE_DT) = 1
) LKP_DT
  ON LKP_DT.FULL_DATE_DT = TRUNC(SRC.TRANSACTION_DATE, 'DD')
LEFT JOIN (
    SELECT
        cls.TRAN_CLS_KEY,
        TRIM(UPPER(cls.TRAN_CLS_LVL_1_NM)) AS TRAN_CLS_LVL_1_NM,
        TRIM(UPPER(cls.TRAN_CLS_LVL_2_NM)) AS TRAN_CLS_LVL_2_NM,
        TRIM(UPPER(cls.TRAN_CLS_LVL_3_NM)) AS TRAN_CLS_LVL_3_NM,
        TRIM(UPPER(cls.TRAN_CLS_LVL_4_NM)) AS TRAN_CLS_LVL_4_NM,
        TRIM(UPPER(cls.TRAN_CLS_LVL_5_NM)) AS TRAN_CLS_LVL_5_NM
    FROM feladm.FEL_TRAN_CLASS_DIM cls
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TRIM(UPPER(cls.TRAN_CLS_LVL_1_NM)), TRIM(UPPER(cls.TRAN_CLS_LVL_2_NM)),
                     TRIM(UPPER(cls.TRAN_CLS_LVL_3_NM)), TRIM(UPPER(cls.TRAN_CLS_LVL_4_NM)),
                     TRIM(UPPER(cls.TRAN_CLS_LVL_5_NM))
        ORDER BY cls.TRAN_CLS_KEY) = 1
) LKP_TC
  ON LKP_TC.TRAN_CLS_LVL_1_NM = SRC.O_TRAN_CLASS_LVL1
 AND LKP_TC.TRAN_CLS_LVL_2_NM = SRC.O_TRAN_CLASS_LVL2
 AND LKP_TC.TRAN_CLS_LVL_3_NM = SRC.O_TRAN_CLASS_LVL3
 AND LKP_TC.TRAN_CLS_LVL_4_NM = SRC.O_TRAN_CLASS_LVL4
 AND LKP_TC.TRAN_CLS_LVL_5_NM = SRC.O_TRAN_CLASS_LVL5
LEFT JOIN (
    SELECT dim.ACCT_TYP_KEY, UPPER(TRIM(dim.ACCT_TYP_NM)) AS ACCT_TYP_NM
    FROM feladm.FEL_ACCT_TYP_DIM dim
    QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(dim.ACCT_TYP_NM)) ORDER BY dim.ACCT_TYP_KEY) = 1
) LKP_AT
  ON LKP_AT.ACCT_TYP_NM = SRC.O_ACCTTYPECLASSNAME
LEFT JOIN (
    SELECT
        iloc.INVTRY_LOC_KEY,
        TRIM(UPPER(iloc.INVTRY_CMDTY_NM))      AS INVTRY_CMDTY_NM,
        TRIM(UPPER(iloc.INVTRY_CMDTY_TYPE_NM)) AS INVTRY_CMDTY_TYPE_NM,
        iloc.INVTRY_PRMRY_FCLTY_KEY,
        iloc.INVTRY_SCNDRY_FCLTY_KEY,
        iloc.INVTRY_LOC_ID,
        iloc.SYSTEM_ID
    FROM feladm.FEL_INVTRY_LOC_DIM iloc
    QUALIFY ROW_NUMBER() OVER (PARTITION BY iloc.INVTRY_LOC_ID, iloc.SYSTEM_ID ORDER BY iloc.INVTRY_LOC_KEY) = 1
) LKP_IL
  ON LKP_IL.INVTRY_LOC_ID = CAST(SRC.INV_LOC_ID AS NUMBER(10,0))
 AND LKP_IL.SYSTEM_ID     = SRC.V_SYSTEM_ID
LEFT JOIN (
    SELECT
        aloc.ACCTG_INVTRY_LOC_KEY,
        TRIM(UPPER(aloc.ACCTG_INVTRY_LOC_NM))  AS ACCTG_INVTRY_LOC_NM,
        TRIM(UPPER(aloc.INVTRY_CMDTY_TYPE_NM)) AS INVTRY_CMDTY_TYPE_NM,
        TRIM(UPPER(aloc.INVTRY_CMDTY_NM))      AS INVTRY_CMDTY_NM
    FROM feladm.FEL_ACCTG_INVTRY_LOC_DIM aloc
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TRIM(UPPER(aloc.ACCTG_INVTRY_LOC_NM)),
                     TRIM(UPPER(aloc.INVTRY_CMDTY_TYPE_NM)),
                     TRIM(UPPER(aloc.INVTRY_CMDTY_NM))
        ORDER BY aloc.ACCTG_INVTRY_LOC_KEY) = 1
) LKP_AL
  ON LKP_AL.ACCTG_INVTRY_LOC_NM  = NVL(LTRIM(RTRIM(SRC.O_ACCT_INV_LOC_NM)), '') || ' (' || NVL(LTRIM(RTRIM(LKP_IL.INVTRY_CMDTY_NM)), '') || ')'
 AND LKP_AL.INVTRY_CMDTY_TYPE_NM = LKP_IL.INVTRY_CMDTY_TYPE_NM
 AND LKP_AL.INVTRY_CMDTY_NM      = LKP_IL.INVTRY_CMDTY_NM
LEFT JOIN (
    SELECT BSNS_ENTY_KEY, FACILITY_KEY, SYSTEM_ID
    FROM feladm.FEL_FACILITY_DIM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY FACILITY_KEY, SYSTEM_ID ORDER BY FACILITY_KEY, SYSTEM_ID) = 1
) LKP_FAC
  ON LKP_FAC.FACILITY_KEY = LKP_IL.INVTRY_SCNDRY_FCLTY_KEY
 AND LKP_FAC.SYSTEM_ID    = SRC.V_SYSTEM_ID
LEFT JOIN (
    SELECT BSNS_ENTY_KEY, BSNS_ENTY_ID, SYSTEM_ID
    FROM feladm.FEL_BSNS_ENTY_DIM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY BSNS_ENTY_ID, SYSTEM_ID ORDER BY BSNS_ENTY_ID, SYSTEM_ID) = 1
) LKP_JOBE
  ON LKP_JOBE.BSNS_ENTY_ID = CAST(SRC.JO_BSNS_ENTY_ID AS NUMBER(10,0))
 AND LKP_JOBE.SYSTEM_ID    = SRC.V_SYSTEM_ID
LEFT JOIN (
    SELECT DIM.CONTRACT_KEY, TRIM(UPPER(DIM.CONTRACT_ID)) AS CONTRACT_ID, DIM.SYSTEM_ID
    FROM feladm.FEL_CONTRACT_DIM DIM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(DIM.CONTRACT_ID)), DIM.SYSTEM_ID ORDER BY DIM.CONTRACT_KEY) = 1
) LKP_CN
  ON LKP_CN.CONTRACT_ID = SRC.O_CNTRCT_ID
 AND LKP_CN.SYSTEM_ID   = SRC.V_SYSTEM_ID
LEFT JOIN (
    SELECT CNTRCT_PROD_KEY, CNTRCT_DTL_ID
    FROM feladm.FEL_CNTRCT_PROD_CD_DIM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY CNTRCT_DTL_ID ORDER BY CNTRCT_PROD_KEY) = 1
) LKP_CP
  ON LKP_CP.CNTRCT_DTL_ID = CAST(SRC.CNTRCTDTL_ID AS NUMBER(10,0))
LEFT JOIN (
    SELECT F.UNIT_KEY, TRIM(F.UNIT_ID) AS UNIT_ID, F.SYSTEM_ID
    FROM feladm.FEL_GNRTN_UNIT_DIM F
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(F.UNIT_ID), F.SYSTEM_ID ORDER BY F.UNIT_KEY) = 1
) LKP_GU
  ON LKP_GU.UNIT_ID   = SRC.O_GEN_UNIT_ID
 AND LKP_GU.SYSTEM_ID = SRC.V_SYSTEM_ID
LEFT JOIN (
    SELECT UPPER(TRIM(VW.ACCOUNT)) AS ACCOUNT
    FROM feladm.PS_Z_GL_ACCT_DIM VW
    QUALIFY ROW_NUMBER() OVER (PARTITION BY UPPER(TRIM(VW.ACCOUNT)) ORDER BY UPPER(TRIM(VW.ACCOUNT))) = 1
) LKP_GL
  ON LKP_GL.ACCOUNT = LTRIM(RTRIM(UPPER(SRC.CF_GL_ACCT)))
LEFT JOIN (
    SELECT reg.EPM_BUS_UNIT_GL_ID, TRIM(UPPER(reg.BUSINESS_UNIT_GL)) AS BUSINESS_UNIT_GL
    FROM feladm.PS_Z_REG_CONS_DIM_VW reg
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(reg.BUSINESS_UNIT_GL)) ORDER BY reg.EPM_BUS_UNIT_GL_ID) = 1
) LKP_RC
  ON LKP_RC.BUSINESS_UNIT_GL = LTRIM(RTRIM(UPPER(SRC.CF_GL_BUS_UNIT)))
LEFT JOIN (
    SELECT VW.EPM_DEPT_ID, TRIM(UPPER(VW.DEPTID)) AS DEPTID
    FROM feladm.PS_Z_DEPT_DIM_VW VW
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(VW.DEPTID)) ORDER BY VW.EPM_DEPT_ID) = 1
) LKP_DEPT
  ON LKP_DEPT.DEPTID = LTRIM(RTRIM(UPPER(SRC.CF_DEPT)))
LEFT JOIN (
    SELECT
        wo.WORK_ORDER_ID,
        TRIM(UPPER(wo.BUSINESS_UNIT_PC))  AS BUSINESS_UNIT_PC,
        TRIM(UPPER(wo.PRIMARY_SOURCE_CD)) AS PRIMARY_SOURCE_CD,
        TRIM(UPPER(wo.PROJECT_ID))        AS PROJECT_ID,
        TRIM(UPPER(wo.ACTIVITY_ID))       AS ACTIVITY_ID
    FROM feladm.AEP_WORK_ORDER_DIM wo
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY TRIM(UPPER(wo.BUSINESS_UNIT_PC)), TRIM(UPPER(wo.PRIMARY_SOURCE_CD)),
                     TRIM(UPPER(wo.PROJECT_ID)), TRIM(UPPER(wo.ACTIVITY_ID))
        ORDER BY wo.WORK_ORDER_ID) = 1
) LKP_WO
  ON LKP_WO.BUSINESS_UNIT_PC  = LTRIM(RTRIM(UPPER(SRC.CF_PROJ_COST_BU)))
 AND LKP_WO.PRIMARY_SOURCE_CD = 'EPM'
 AND LKP_WO.PROJECT_ID        = LTRIM(RTRIM(UPPER(SRC.CF_PROJECT)))
 AND LKP_WO.ACTIVITY_ID       = LTRIM(RTRIM(UPPER(SRC.CF_WORK_ORDER)))
LEFT JOIN (
    SELECT VW.EPM_PROJECT_ID, TRIM(UPPER(VW.PROJECT_ID)) AS PROJECT_ID
    FROM feladm.PS_Z_PROJ_DIM VW
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(VW.PROJECT_ID)) ORDER BY VW.EPM_PROJECT_ID) = 1
) LKP_PROJ
  ON LKP_PROJ.PROJECT_ID = LTRIM(RTRIM(UPPER(SRC.CF_PROJECT)))
LEFT JOIN (
    SELECT VW.EPM_RSRC_TYPE_ID, TRIM(UPPER(VW.RESOURCE_TYPE)) AS RESOURCE_TYPE
    FROM feladm.PS_Z_COST_CLS_DIM VW
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(VW.RESOURCE_TYPE)) ORDER BY VW.EPM_RSRC_TYPE_ID) = 1
) LKP_CC
  ON LKP_CC.RESOURCE_TYPE = 'UNKWN'
LEFT JOIN (
    SELECT TRIM(UPPER(wo.BUSINESS_UNIT_PC)) AS BUSINESS_UNIT_PC
    FROM feladm.AEP_WORK_ORDER_DIM wo
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(wo.BUSINESS_UNIT_PC)) ORDER BY TRIM(UPPER(wo.BUSINESS_UNIT_PC))) = 1
) LKP_PCBU
  ON LKP_PCBU.BUSINESS_UNIT_PC = LTRIM(RTRIM(UPPER(SRC.CF_PROJ_COST_BU)))
LEFT JOIN (
    SELECT TRIM(DIM.RESOURCE_SUB_CAT) AS RESOURCE_SUB_CAT
    FROM feladm.PS_Z_RES_S_CAT_DIM DIM
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(DIM.RESOURCE_SUB_CAT) ORDER BY TRIM(DIM.RESOURCE_SUB_CAT)) = 1
) LKP_RSC
  ON LKP_RSC.RESOURCE_SUB_CAT = LTRIM(RTRIM(SRC.CF_RESOURCE_CAT))
LEFT JOIN (
    SELECT VW.EPM_ABM_ACTV_ID, TRIM(UPPER(VW.RESOURCE_CATEGORY)) AS RESOURCE_CATEGORY
    FROM feladm.PS_Z_PROCS_ACT_DIM VW
    QUALIFY ROW_NUMBER() OVER (PARTITION BY TRIM(UPPER(VW.RESOURCE_CATEGORY)) ORDER BY VW.EPM_ABM_ACTV_ID) = 1
) LKP_ABM
  ON LKP_ABM.RESOURCE_CATEGORY = LTRIM(RTRIM(UPPER(SRC.CF_ABM_ACTIVITY)));
